import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "internship-project",
  description: "Generated by create next app",
};
import { Poppins, Urbanist } from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-urbanist",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
   variable: "--font-poppins",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
      className={`${poppins.variable} ${urbanist.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
